name: towards-cml
on: [push]
jobs:
  my-cml:
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - uses: iterative/setup-cml@v2
      - name: cml-run
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Hello World!"
