name: towards-cml
on: [push]
jobs:
  my-cml:
    runs-on: [ubuntu-latest]
    # container: docker://dvcorg/cml-py3:latest
    steps: 
      - uses: actions/checkout@v2
      - name: cml-run
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Hello World!"
            
